Task23_Library_MVC_Framework/Controllers/GuestController.cs
using System;
using System.Collections.Generic;
using System.Web.Mvc;
using Task23_Library_MVC_Framework.Models;
using Task23_Library_MVC_Framework.UOfW;

namespace Task23_Library_MVC_Framework.Controllers
{
    public class GuestController : Controller
    {
        /// <summary>
        /// Loads Comments from Db
        /// </summary>
        /// <returns>Comments Page</returns>
        public ActionResult Index()
        {
            var unitOfWork = new UnitOfWork();
            return View(unitOfWork.CommentRepository.Get());
        }

        /// <summary>
        /// Adds comment to Db
        /// </summary>
        /// <param name="comment"></param>
        /// <returns>Add comment</returns>
        [HttpPost]
        public ActionResult AddComment(Comment comment)
        {
            if (string.IsNullOrEmpty(comment.Name))
                ModelState.AddModelError("Name", "Error! Please enter your name!");

            if (string.IsNullOrEmpty(comment.Text))
                ModelState.AddModelError("Text", "Error! Please enter your text!");

            var unitOfWork = new UnitOfWork();

            if (ModelState.IsValid)
            {
                unitOfWork.CommentRepository.InsertOrUpdate(comment);
                unitOfWork.Save();
                return RedirectToAction("Index");
            }

            return View("Index", unitOfWork.CommentRepository.Get());
        }
    }
}

Task23_Library_MVC_Framework/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET MVC Framework Library</title>
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/styles.css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="wrapper">
        <header>
            <nav class="navbar navbar-expand-md navbar-light bg-light">
                <img class="navbar-brand img-logo" src="~/Images/logo.png" alt="Book"/>
                <p class="navbar-header mx-auto">MVC Framework Library</p>
            </nav>
        </header>
        <div class="main-content">
            <div class="container-fluid">
                <div class="col-10 float-left">
                    @RenderBody()
                </div>
                <div class="right-sidebar col-2 float-left text-center">
                    <ul>
                        <li>@Html.ActionLink("Main", "Index", "Home")</li>
                        <li>@Html.ActionLink("Comments", "Index", "Guest")</li>
                        <li>@Html.ActionLink("Form", "Index", "Form")</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <footer>
        <div class="container-fluid">
            <div class="row text-center">
                <p class="col-12">Copyright &copy; @DateTime.Now.Year. All Rights Reserved. Serhii Kovalov andrey_roland@hotmail.com <br /> <a class="col-12" href="#top">Go back to top</a> </p>
            </div>
        </div>
    </footer>

    @Scripts.Render("~/bundles/jquery")
    @RenderSection("scripts", required: false)

</body>
</html>